### ISSUE TITLE
socket tests and redirection tests does not clean up bpf_object on failure

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#2203]
The socket and redirect tests allocate bpf object on heap during test variation setup. Since Catch2::REQUIRE throws an exception upon failure, the bpf_object does not get closed. This causes problem for the next variation that will fail to load the eBPF program as it is still loaded. So when one of these tests fail, all subsequent tests fail.

One solution could be to have a `std::unique_ptr` wrapper class around bpf_object used in these tests.

**Comment by delaramamiri** [comment]
Resolved by [PR #2450 ](https://github.com/microsoft/ebpf-for-windows/pull/2450)

**Comment by shankarseal** [comment]
I am reopening as #2226 was reverted by #2419. Although #2450 fixes the issue for connect redirect tests. The issue remains with socket_tests.cpp. Maybe a similar fix as #2450 can be take for socket_tests as well. @delaramamiri please do the needful.

**Comment by rectified95** [comment]
@shankarseal I couldn't reproduce on my first try.

I forced an assertion failure right after the `bpf_object` load at https://github.com/microsoft/ebpf-for-windows/blob/e29d4041b7d7f7a02bd54a632194783228c565e9/tests/socket/socket_tests.cpp#L45
```
REQUIRE(bpf_object__load(object) == 0);
if (address_family == AF_INET && protocol == IPPROTO_UDP) {
    REQUIRE(false);
}
```
and only saw the first of the four `connection_test` calls fail, so the cascading effect wasn't there.
Can you help me get a repro?

**Comment by shankarseal** [comment]
This issue was first found in connect_redirect tests which used .o files only at that time. I think attaching the same program to the sock_addr hook caused an issue and Gianni fixed it using #2450 . The same problem existed in the socket tests but not addressed at that time.

`_native_module_helper::initialize` generates random file name and that is why this is working. 
To reproduce the failure try removing the following:
```
        // Generate a random GUID to append to the file name.
        REQUIRE(UuidCreate(&random_guid) == RPC_S_OK);
```
or you could try the JIT variation of the tests - which you can get if you used a build that is NOT native only. I think with .o files attaching multiple times will cause a failure.

**Comment by rectified95** [comment]
Didn't repro in JIT mode, either. Perhaps this got fixed somehow.
I can spend some time looking for confirmation in the code, otherwise I'd close as non-repro.
![image](https://github.com/microsoft/ebpf-for-windows/assets/12816515/a972f5b8-9c2c-409f-bbc4-56b893558ca2)
